'use client';

import { useEffect,useState } from 'react';
import {readSheet as readXlsxFile} from 'read-excel-file/browser';
import Brand from '@/app/components/Brand';

type Row=Record<string,unknown>;
const templateHeaders=['locality','property_type','bedrooms','strategy','monthly_price','nightly_rate','occupancy','electricity_included','water_included','internet_included','building_fees_included'];

function parseCsv(text:string){
  const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return[];
  const parse=(line:string)=>{const values:string[]=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&line[i+1]==='"'){value+='"';i++;}else if(char==='"'){quoted=!quoted;}else if(char===','&&!quoted){values.push(value.trim());value='';}else value+=char;}values.push(value.trim());return values};
  const headers=parse(lines[0]).map(value=>value.toLowerCase().replace(/\s+/g,'_'));
  return lines.slice(1).map(line=>Object.fromEntries(parse(line).map((value,index)=>[headers[index],value])));
}

export default function AdminClient(){
  const [rows,setRows]=useState<Row[]>([]),[fileName,setFileName]=useState(''),[message,setMessage]=useState(''),[summary,setSummary]=useState<{count:number;updated_at:number|null}|null>(null),[uploading,setUploading]=useState(false);
  useEffect(()=>{fetch('/api/admin/comparables').then(response=>response.ok?response.json() as Promise<{count:number;updated_at:number|null}>:null).then(setSummary)},[]);
  const choose=async(file:File)=>{setFileName(file.name);setMessage('');if(file.name.toLowerCase().endsWith('.csv'))setRows(parseCsv(await file.text()));else{const sheet=await readXlsxFile(file);const [headers,...data]=sheet;const normalized=headers.map(value=>String(value??'').toLowerCase().replace(/\s+/g,'_'));setRows(data.filter(row=>row.some(value=>value!==null)).map(row=>Object.fromEntries(row.map((value,index)=>[normalized[index],value]))));}};
  const upload=async()=>{setUploading(true);setMessage('');try{const response=await fetch('/api/admin/comparables',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({rows})});const data=await response.json() as {error?:string;imported:number;updatedAt:number};if(!response.ok)throw new Error(data.error??'Upload failed');setMessage(`${data.imported} comparables imported successfully.`);setSummary({count:data.imported,updated_at:data.updatedAt});}catch(error){setMessage(error instanceof Error?error.message:'Upload failed');}finally{setUploading(false)}};
  const downloadTemplate=()=>{const example=['Sliema','apartment','2','long-term','2200','0','0','yes','yes','no','yes'];const blob=new Blob([`${templateHeaders.join(',')}\n${example.join(',')}\n`],{type:'text/csv'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='ownly-market-template.csv';anchor.click();URL.revokeObjectURL(url)};
  return <main className="admin-page"><header><Brand href="/dashboard"/><a href="/admin/airbnb">Airbnb collector →</a><a href="/dashboard">← Back to dashboard</a></header><section className="admin-hero"><div><span className="kicker">MARKET DATA ADMIN</span><h1>Upload comparable properties.</h1><p>Replace the current market dataset with a reviewed CSV or Excel file. Users are automatically matched by locality, property type, bedrooms and rental strategy.</p></div><div className="dataset-status"><span>CURRENT DATASET</span><strong>{summary?.count??0}</strong><p>comparable properties</p><small>{summary?.updated_at?`Last updated ${new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'}).format(summary.updated_at)}`:'No dataset uploaded'}</small></div></section><section className="admin-card"><div className="admin-card-head"><div><h2>1. Prepare the file</h2><p>Use the exact template columns. Boolean service fields accept yes/no.</p></div><button className="outline-button compact" onClick={downloadTemplate}>Download CSV template</button></div><div className="column-list">{templateHeaders.map(header=><code key={header}>{header}</code>)}</div></section><section className="admin-card"><h2>2. Choose CSV or Excel</h2><label className="upload-zone"><input type="file" accept=".csv,.xlsx,.xls" onChange={event=>event.target.files?.[0]&&choose(event.target.files[0])}/><b>{fileName||'Drop or choose a file'}</b><span>CSV, XLSX or XLS · maximum 5,000 rows</span></label>{rows.length>0&&<><div className="upload-summary"><span><b>{rows.length}</b> rows ready</span><span>Preview of first {Math.min(5,rows.length)}</span></div><div className="preview-table"><table><thead><tr>{templateHeaders.slice(0,6).map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{rows.slice(0,5).map((row,index)=><tr key={index}>{templateHeaders.slice(0,6).map(header=><td key={header}>{String(row[header]??'—')}</td>)}</tr>)}</tbody></table></div><div className="admin-actions"><p>This replaces the current dataset. Existing customer properties are not changed.</p><button className="button" disabled={uploading} onClick={upload}>{uploading?'Importing…':'Replace market dataset →'}</button></div></>}{message&&<p className={`admin-message ${message.includes('successfully')?'success':''}`}>{message}</p>}</section></main>;
}
