'use client';
import {useEffect,useState} from 'react';
import Brand from '@/app/components/Brand';
import {areas,Query} from '@/lib/airbnb/normalize';
import './airbnb.css';
import AutomaticSearches from './AutomaticSearches';
type Row={id:string;name:string;url:string;locality:string;property_type:string;bedrooms:number;total_cents:number;nights:number;observed_at:string};
type Data={rows:Row[];totalStored:number;collectorConnected:boolean};
const sample:Query={area:"St. Paul's Bay",checkin:'2026-09-25',checkout:'2026-09-27',adults:4,bedrooms:2,pages:3};
const money=(n:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(n);
export default function AirbnbClient(){
 const [automatic,setAutomatic]=useState(false);
 const [q,setQ]=useState<Query>(sample),[applied,setApplied]=useState<Query>(sample),[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[failed,setFailed]=useState(false);
 async function search(query:Query){const r=await fetch('/api/admin/airbnb?'+new URLSearchParams(Object.fromEntries(Object.entries(query).map(([k,v])=>[k,String(v)]))));const d=await r.json() as Data & {error?:string};if(!r.ok)throw Error(d.error||'Search failed');setData(d);setApplied(query);}
 useEffect(()=>{search(sample).catch(e=>{setMessage(e.message);setFailed(true);});},[]);
 async function run(action:string,captures?:unknown[]){setBusy(action);setMessage('');setFailed(false);try{
 if(action==='search')await search(q);
 else {const r=await fetch('/api/admin/airbnb',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,query:q,captures})});const d=await r.json() as {error?:string;inserted:number;accepted:number;rejected:number;warnings?:string[]};if(!r.ok)throw Error(d.error||'Import failed');
 const query=action==='sample'?sample:q;if(action==='sample')setQ(sample);await search(query);setMessage(`${d.inserted} observations added · ${d.accepted-d.inserted} already stored · ${d.rejected} cards excluded (dates, bedrooms or price).${d.warnings?.length?' Partial capture: '+d.warnings.join(' '):''}`);}
 }catch(e){setFailed(true);setMessage(e instanceof Error?e.message:'Something went wrong.');}finally{setBusy('');}}
 async function upload(file:File){try{if(file.size>2000000)throw Error('Maximum file size: 2 MB.');const b=JSON.parse(await file.text());await run('import',b.captures??(Array.isArray(b)?b:[b]));}catch(e){setFailed(true);setMessage(e instanceof Error?e.message:'Invalid JSON.');}}
 const prices=(data?.rows??[]).map(r=>r.total_cents/100/r.nights).sort((a,b)=>a-b);const median=prices.length?(prices[Math.floor((prices.length-1)/2)]+prices[Math.floor(prices.length/2)])/2:null;
 return <main className="airbnb-page"><header className="ab-nav"><Brand href="/dashboard"/><nav><a href="/admin">CSV / Excel imports</a><a href="/dashboard">← Dashboard</a></nav></header>
 <section className="ab-hero"><div><span className="ab-eyebrow">OWNLY / MARKET DATA</span><h1>A clearer view of<br/>Airbnb prices.</h1><p>Collect comparable stays. Keep the evidence.<br/>Build your Malta market database, one search at a time.</p></div><div className="ab-source"><span className="ab-dot"/> AIRBNB<span>Advertised stay prices · EUR</span><small>{data?.totalStored??0} observations stored</small></div></section>
 <section className="ab-card"><div className="ab-heading"><div><h2>Define your comparison</h2><p>Bedrooms, guests and dates must match exactly.</p></div><span className="ab-tag">ADMIN WORKSPACE</span></div>
 <form onSubmit={e=>{e.preventDefault();run('search');}}><div className="ab-fields"><label>Area<select value={q.area} onChange={e=>setQ({...q,area:e.target.value})}>{areas.map(a=><option key={a}>{a}</option>)}</select></label><label>Bedrooms<input type="number" min="1" max="10" required value={q.bedrooms} onChange={e=>setQ({...q,bedrooms:Number(e.target.value)})}/></label><label>Guests<input type="number" min="1" max="16" required value={q.adults} onChange={e=>setQ({...q,adults:Number(e.target.value)})}/></label><label>Check-in<input type="date" required value={q.checkin} onChange={e=>setQ({...q,checkin:e.target.value})}/></label><label>Check-out<input type="date" required value={q.checkout} onChange={e=>setQ({...q,checkout:e.target.value})}/></label><label>Pages<select value={q.pages} onChange={e=>setQ({...q,pages:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div>
 <div className="ab-actions"><button className="button" type="submit" disabled={!!busy}>{busy==='search'?'Searching…':'Search saved data →'}</button>{!automatic&&<button className="outline-button" type="button" disabled={!!busy||!data?.collectorConnected} onClick={()=>run('collect')}>{busy==='collect'?'Collecting Airbnb prices…':'Collect from Airbnb & save'}</button>}<span>{automatic?'Automatic collector available below':data?.collectorConnected?'Collector configured':'Live collector not connected'}</span></div></form>
 {!automatic&&!data?.collectorConnected&&<p className="ab-note">You can load the verified dataset or import collector JSON now. New live searches become available once the Docker collector is connected.</p>}</section>
 <AutomaticSearches query={q} onSaved={()=>search(q).catch(e=>setMessage(e.message))} onAvailability={setAutomatic}/><section className="ab-import"><div><h2>Start with real observations</h2><p>Verified capture · 18 Sep 2026 · St. Paul’s Bay search · 25–27 Sep · 4 guests · 2 bedrooms. Repeated imports do not duplicate records.</p></div><div className="ab-import-actions"><button className="outline-button" disabled={!!busy} onClick={()=>run('sample')}>{busy==='sample'?'Saving…':'Load verified dataset'}</button><label className={'ab-file '+(busy?'ab-disabled':'')}>Import capture JSON<input type="file" accept=".json,application/json" disabled={!!busy} onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);e.target.value='';}}/></label></div></section>
 {message&&<p role={failed?'alert':'status'} className={'ab-message '+(failed?'ab-error':'')}>{message}</p>}
 <section aria-label="Price summary" className="ab-stats"><div><span>Matching listings</span><strong>{prices.length}</strong><small>Latest observation per listing</small></div><div><span>Median per night</span><strong>{median===null?'—':money(median)}</strong><small>Displayed stay total ÷ nights</small></div><div><span>Advertised range / night</span><strong>{prices.length?`${money(prices[0])} – ${money(prices.at(-1)!)}`:'—'}</strong><small>Not host earnings or occupancy</small></div></section>
 <section className="ab-card"><div className="ab-heading"><div><h2>Your comparables</h2><p>{applied.area} · {applied.bedrooms} bedrooms · {applied.adults} guests · {applied.checkin} → {applied.checkout}</p></div><span className="ab-tag">LATEST SAVED PRICES</span></div>
 {data?.rows.length?<div className="ab-table"><table><thead><tr><th>Listing</th><th>Stay total</th><th>Per night</th><th>Observed</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.id}><td><a href={r.url} target="_blank" rel="noopener noreferrer">{r.name} ↗</a><small>{r.property_type} · {r.locality}</small></td><td>{money(r.total_cents/100)}<small>{r.nights} nights</small></td><td>{money(r.total_cents/100/r.nights)}</td><td>{new Date(r.observed_at).toLocaleDateString('en-GB')}<small>{new Date(r.observed_at).toISOString().slice(11,16)} UTC</small></td></tr>)}</tbody></table></div>:<div className="ab-empty"><strong>No saved matches yet.</strong><p>Load the verified dataset, import a capture, or adjust your search.</p></div>}
 <p className="ab-footnote">Area matching uses the listing’s displayed locality, not a verified radius. Results are a visible-page sample, not the entire market. Prices can change; taxes and fees follow Airbnb’s displayed total. No occupancy, revenue or host contact data is inferred.</p></section></main>;
}
