'use client';
import {useEffect,useState,useRef} from 'react';
import type {Query} from '@/lib/airbnb/normalize';
type Saved={id:string;query:Query;interval_days:number;enabled:number;next_run:number};
type Run={id:string;search_id:string;status:string;query:Query;inserted:number|null;error:string|null};
type State={available:boolean;searches:Saved[];runs:Run[]};
export default function AutomaticSearches({query,onSaved,onAvailability}:{query:Query;onSaved:()=>void;onAvailability:(available:boolean)=>void}){
 const notified=useRef(new Set<string>());const callbacks=useRef({onSaved,onAvailability});callbacks.current={onSaved,onAvailability};
 const [state,setState]=useState<State|null>(null),[interval,setIntervalDays]=useState(3),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let stopped=false;async function poll(){try{const r=await fetch('/api/admin/airbnb-jobs');if(!r.ok)throw Error('Cannot read automatic searches');const d=await r.json() as State;if(!stopped){setState(d);callbacks.current.onAvailability(d.available);for(const run of d.runs??[])if(['completed','partial'].includes(run.status)&&!notified.current.has(run.id)){notified.current.add(run.id);callbacks.current.onSaved();}}}catch(e){if(!stopped)setError(e instanceof Error?e.message:'Cannot read searches');}}poll();const timer=window.setInterval(poll,5000);return()=>{stopped=true;window.clearInterval(timer);};},[]);
 async function action(action:string,id?:string){setBusy(true);setError('');try{const r=await fetch('/api/admin/airbnb-jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,query,intervalDays:interval})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Could not save search');const updated=await fetch('/api/admin/airbnb-jobs');setState(await updated.json() as State);}catch(e){setError(e instanceof Error?e.message:'Could not save search');}finally{setBusy(false);}}
 if(!state?.available)return <p className="ab-note">Automatic search schedules are available in the Docker installation.{error?' '+error:''}</p>;
 return <section className="ab-card"><div className="ab-heading"><div><h2>Automatic searches</h2><p>Use the search filters above. Results are collected and saved in the background.</p></div></div><div className="ab-actions"><label>Repeat <select aria-label="Search frequency" value={interval} onChange={e=>setIntervalDays(Number(e.target.value))}><option value={0}>Once</option><option value={3}>Every 3 days</option><option value={7}>Every 7 days</option></select></label><button className="button" disabled={busy} onClick={()=>action('create')}>Save search & start</button><button className="outline-button" onClick={onSaved}>Refresh saved prices</button></div><p className="ab-footnote">Recurring searches move the stay dates forward as time passes, preserving the initial lead time and number of nights. Keep Docker running; the browser can be closed.</p>{error&&<p role="alert" className="ab-message ab-error">{error}</p>}
 {state.searches.map(s=><div className="ab-saved-search" key={s.id}><div><strong>{s.query.area} · {s.query.bedrooms} bedrooms · {s.query.adults} guests</strong><p>{s.query.checkin} → {s.query.checkout} · {s.interval_days?`Every ${s.interval_days} days`:'One-time search'} · {s.enabled?'Scheduled':'Not scheduled'}</p>{Boolean(s.enabled)&&<small>Next run: {new Date(s.next_run).toLocaleString()}</small>}</div><div className="ab-actions"><button className="outline-button" disabled={busy} onClick={()=>action('run',s.id)}>Run now</button>{s.interval_days>0&&<button className="outline-button" disabled={busy} onClick={()=>action(s.enabled?'pause':'resume',s.id)}>{s.enabled?'Pause':'Resume'}</button>}</div></div>)}
 {state.runs.length>0&&<div className="ab-table"><table><thead><tr><th>Search</th><th>Stay</th><th>Status</th><th>Saved</th></tr></thead><tbody>{state.runs.slice(0,15).map(r=><tr key={r.id}><td>{r.query.area}</td><td>{r.query.checkin} → {r.query.checkout}</td><td>{r.status}{r.error&&<small>{r.error}</small>}</td><td>{r.inserted??'—'}</td></tr>)}</tbody></table></div>}</section>;
}
